const assets=[['SW-NP-CORE-01','Network Switch','Cisco IE-3400','10.24.1.11','North Plant','Gi1/0/1 · VLAN 10','Active'],['SW-NP-AREA-A-01','Network Switch','Cisco IE-3300','10.24.2.21','North Plant · Area A','Gi1/0/2 · VLAN 20','Active'],['SW-NP-AREA-B-01','Network Switch','Hirschmann RSP35','10.24.3.21','North Plant · Area B','Port 1 · VLAN 30','Active'],['PLC-NP-01','PLC','Siemens S7-1500','10.24.2.50','North Plant · Area A','—','Active'],['HMI-NP-01','HMI','Siemens Comfort Panel','10.24.2.61','North Plant · Area A','—','Active'],['ENG-NP-01','Engineering Workstation','Dell OptiPlex','10.24.1.81','North Plant','—','Active']];
const controls=[['SW-AC-001','Secure remote management','transport input ssh','High','Network Switch','Disable Telnet and permit SSH only.'],['SW-AU-003','AAA authentication enabled','aaa new-model','High','Network Switch','Enable AAA with a named authentication method.'],['SW-DC-002','Unused ports are disabled','shutdown','Medium','Network Switch','Administratively shut down unused switch interfaces.'],['SW-NM-004','SNMPv3 configured','snmp-server group SEC v3 priv','High','Network Switch','Replace SNMPv2 community strings with SNMPv3.'],['SW-LO-001','Central logging enabled','logging host 10.24.1.15','Medium','Network Switch','Forward events to the approved SIEM server.'],['SW-TS-002','NTP authentication enabled','ntp authenticate','Medium','Network Switch','Configure authenticated NTP sources.']];
const findings=[['SW-AC-001','Secure remote management','SW-NP-AREA-A-01','transport input ssh telnet','transport input ssh','Non-Compliant','High','Disable Telnet and permit SSH only.'],['SW-AU-003','AAA authentication enabled','SW-NP-CORE-01','Not detected','aaa new-model','Non-Compliant','High','Enable AAA with a named authentication method.'],['SW-DC-002','Unused ports are disabled','SW-NP-AREA-B-01','Gi1/0/23: no shutdown','shutdown','Non-Compliant','Medium','Administratively shut down unused interfaces.'],['SW-NM-004','SNMPv3 configured','SW-NP-AREA-A-01','snmp-server community public RO','snmp-server group SEC v3 priv','Non-Compliant','High','Replace SNMPv2 community strings with SNMPv3.'],['SW-LO-001','Central logging enabled','SW-NP-CORE-01','logging host 10.24.1.15','logging host 10.24.1.15','Compliant','Medium','Forward events to the approved SIEM server.'],['SW-TS-002','NTP authentication enabled','SW-NP-AREA-B-01','Not applicable','ntp authenticate','Not Applicable','Medium','Configure authenticated NTP sources.']];
const configRows=[['SW-NP-CORE-01','Cisco IE-3400','10.24.1.11','SW-NP-CORE-01_running.cfg','Parsed'],['SW-NP-AREA-A-01','Cisco IE-3300','10.24.2.21','SW-NP-AREA-A-01.txt','Parsed'],['SW-NP-AREA-B-01','Hirschmann RSP35','10.24.3.21','—','Awaiting upload'],['SW-NP-AREA-C-01','Cisco IE-3300','10.24.4.21','SW-NP-AREA-C-01.txt','Parsed'],['SW-NP-UTIL-01','Cisco IE-3400','10.24.1.31','—','Awaiting upload']];
const assessments=[['North Plant OT — July 2026','Jul 14, 2026','IEC 62443 v2.4','48','78%','In progress'],['North Plant OT — May 2026','May 28, 2026','IEC 62443 v2.3','42','73.8%','Complete'],['North Plant OT — February 2026','Feb 18, 2026','IEC 62443 v2.3','42','69.6%','Complete']];
let role='Admin';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function status(v){let c=v==='Complete'||v==='Parsed'?'complete':v==='In progress'?'in-progress':v==='Awaiting upload'?'na-status':v==='Compliant'?'compliant-status':v==='Non-Compliant'?'noncompliant-status':'na-status';return `<span class="status ${c}">${v}</span>`}
function render(){ $('#asset-table').innerHTML=assets.map(a=>`<tr>${a.map((v,i)=>`<td>${i===0?`<strong>${v}</strong>`:i===1?`<span class="count-pill">${v}</span>`:i===6?status(v):v}</td>`).join('')}</tr>`).join(''); $('#inventory-total').textContent=48; $('#baseline-table').innerHTML=controls.map(c=>`<tr>${c.map((v,i)=>`<td class="${i===0?'mono':i===3?v.toLowerCase():''}">${v}</td>`).join('')}</tr>`).join(''); $('#config-table').innerHTML=configRows.map((r,i)=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td><td>${r[2]}</td><td class="mono">${r[3]}</td><td>${status(r[4])}</td><td>${r[4]==='Awaiting upload'?'<button class="link map-one" data-index="'+i+'">Map file</button>':'<button class="link">View parsed data</button>'}</td></tr>`).join(''); renderFindings(); let ah=assessments.map(a=>`<tr>${a.map((v,i)=>`<td>${i===0?`<strong>${v}</strong>`:i===5?status(v):v}</td>`).join('')}<td>›</td></tr>`).join('');$('#recent-assessments').innerHTML=ah;$('#all-assessments').innerHTML=ah; }
function renderFindings(){let f=$('#result-filter')?.value||'all';$('#results-table').innerHTML=findings.filter(r=>f==='all'||r[5]===f).map(r=>`<tr>${r.map((v,i)=>`<td class="${[3,4].includes(i)?'mono':i===6?v.toLowerCase():''}">${i===0?`<strong>${v}</strong>`:i===5?status(v):v}</td>`).join('')}</tr>`).join('')}
function toast(message){let t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function navigate(page){$$('.page').forEach(p=>p.classList.remove('active'));$('#'+page).classList.add('active');$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#breadcrumb').textContent=page.replace(/-/g,' ').toUpperCase();$('.sidebar').classList.remove('open');window.scrollTo(0,0)}
function applyRole(){let restricted=role==='Viewer';$$('[data-admin]').forEach(e=>e.style.display=role==='Admin'?'':'none');$$('[data-assessor]').forEach(e=>e.style.display=restricted?'none':'');$('#user-name').textContent=role==='Admin'?'Alex Morgan':role==='Assessor'?'Jordan Lee':'Sam Taylor';$('#user-role').textContent=role;}
$('#login-form').addEventListener('submit',e=>{e.preventDefault();let u=$('#username').value.toLowerCase(),p=$('#password').value; if(u===p&&['admin','assessor','viewer'].includes(u)){role=u[0].toUpperCase()+u.slice(1);$('#login-screen').classList.add('hidden');$('#app').classList.remove('hidden');applyRole();toast(`Signed in as ${role}`)}else toast('Use one of the demo accounts shown below.')});
$$('[data-demo]').forEach(b=>b.onclick=()=>{$('#username').value=b.dataset.demo;$('#password').value=b.dataset.demo});$$('.nav-link').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$$('[data-page-link]').forEach(b=>b.onclick=()=>navigate(b.dataset.pageLink));$('#logout').onclick=()=>{location.reload()};$('#mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');
$$('[data-new-assessment]').forEach(b=>b.onclick=()=>$('#assessment-modal').classList.remove('hidden'));$('.close-modal').onclick=()=>$('#assessment-modal').classList.add('hidden');$('#create-assessment').onclick=()=>{$('#assessment-modal').classList.add('hidden');navigate('inventory');toast('Assessment created. Upload the asset inventory to continue.')};
['inventory-file','baseline-file','config-file'].forEach(id=>{let el=$('#'+id);el?.addEventListener('change',()=>{if(el.files.length){toast(`${el.files.length} file${el.files.length>1?'s':''} uploaded and validated.`);if(id==='inventory-file'){$('#asset-count').textContent='48';navigate('inventory')}if(id==='config-file'){configRows[2][3]=el.files[0].name;configRows[2][4]='Parsed';render();$('#mapped-count').textContent='13';$('#pending-count').textContent='5'}if(id==='baseline-file')navigate('baseline')}})});
$('#auto-map').onclick=()=>{configRows.forEach((r,i)=>{if(r[4]==='Awaiting upload'){r[3]=r[0]+'.cfg';r[4]='Mapped'}});render();$('#mapped-count').textContent='18';$('#pending-count').textContent='0';toast('Available configuration files mapped to switches.')};$('#config-table').addEventListener('click',e=>{if(e.target.classList.contains('map-one')){let r=configRows[e.target.dataset.index];r[3]=r[0]+'.cfg';r[4]='Mapped';render();toast('Configuration mapped successfully.')}});$('#run-assessment').onclick=()=>{navigate('results');toast('Assessment complete: 123 controls evaluated across 18 switches.')};$('#result-filter').onchange=renderFindings;
$('#download-excel').onclick=()=>{let rows=[['Control ID','Requirement','Asset','Current Configuration','Expected Baseline','Status','Severity','Recommendation'],...findings];let blob=new Blob([rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='OT_Gap_Assessment_July_2026.csv';a.click();URL.revokeObjectURL(a.href);toast('Excel-compatible report downloaded.')};$('#download-pdf').onclick=()=>{navigate('results');setTimeout(()=>window.print(),200);};render();
